shell = "zsh"
apply = ["source"]

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
